lib/adb.js
If the flag is set, adb will not kill the server. See https://github.com/appium/appium/pull/4443
=> Added check for 'adb kill-server' suppress server argument flag

lib/tools/apk-signing.js
The logs get a little sketchy when an app is being signed.
=> Add additional logging to app signing

lib/helpers.js
Turns out that `gunzip` works entirely differently than `unzip`. Decided to just require `unzip` on the system.
=> Undo unzip selection

lib/tools/system-calls.js, test/unit/apk-signing-specs.js
In Windows, Appium 1.5 doesn't find adb comand:
```  
[ADB]Checking whether adb is present
[MJSONWP] Encountered internal error running command: Error: Could not find adb in tools, platform-tools, or supported build-tools under D:\android-sdk do you have the Android SDK installed at this location?
at ADB.callee$0$0$ (lib/tools/system-calls.js:59:11)
```
The complete binary name should be adb.exe.
=> Fix sdk binary names in windows

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
Fixes issue with calling `lock()` in quick succession. Also adding a 500ms delay because ADB doesn't recognize the lock until the animation is complete.
=> lock() fix

lib/tools/system-calls.js, test/unit/syscalls-specs.js
`appium-uiautomator` pulls stuff from adb and then creates a `SubProcess`. This is wrong. So add a method to create one in the context of the adb instance.
=> Add method to create a subprocess of adb

lib/helpers.js, lib/tools/apk-utils.js, test/unit/helper-specs.js
Instead of trying to guess if the activity needs to be made relative, use a list of possible activity names to check if it has started.
Also improve logging so we have more visibility into what is going on.
See https://github.com/appium/appium/issues/5936
=> Use multiple possible activities

lib/tools/android-manifest.js
Resolves https://github.com/appium/appium/issues/6102
- Windows was unable to launch Selendroid Server
- Both OSX and Windows were using the same APK
- The APK, however, produced different package names
- Further inspection of each APK showed differences in the AndroidManifest.xml file
- Windows wasn't inserting the modified AndroidManifest.xml because it couldn't find the move_manifest.jar file
CC @imurchie
=> corrected jar path

lib/tools/system-calls.js, test/unit/syscalls-specs.js
To fix https://github.com/appium/appium/issues/6233, getRunningAVD method should return null when no avd is connected, instead of throwing an exception.
I have also added locale property in launchAVD method to launch API23 emulators with proper language settings.
=> Update getRunningAVD to allow launching Android Emulator

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
The android emulator started echoing command input over Telnet in Android SDK Tools 25.1.1. This fixes #150 and avoids processing echoed command input from telnet.
=> Only use last line of telnet output

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
This will resolve appium/appium#5256 and this will continue in appium/appium-android-driver#148.
Apologies for confusion.Have raised it here.
@imurchie @jlipps @TikhomirovSergey Please review. This fixes the API to work on all the Android API till API Level 23 (Tested from 19 to 23)
=> fixed setWifiState and setDataState for API>19

lib/tools/system-calls.js
The exact error is `error: device '3801b560347ac200' not found`. So I change the Regex to match with that error.
=> Correct Regex for deviceNotFoundError

lib/helpers.js, test/unit/helper-specs.js
The current implementation does not allow intent arguments that have dashes in them. This re-implements the parsing to allow them.
Fixes #161.
=> Fix optional intent argument parsing

lib/helpers.js, test/unit/apk-utils-specs.js
Rather than just launching and allowing things to go on, wait for the launch to happen. See https://github.com/appium/appium/issues/5830 and https://github.com/appium/appium/issues/6505.
=> Add flag so launching apps waits for the launch

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
Android text field clearing is a problem. `adb` can send a key event to delete, and can do it quickly and reliably. Add a method to do that so we can offer a better way to clear, if possible.
=> Add method to clear a text field using adb

lib/tools/system-calls.js
Add a new function to kill emulator with specific AVD name.
This function is required by `appium-android-driver` to be able to wipe-data of running emulator and close emulator at the end of the test.
I was not able to make it work with `teen_process`. Teen_process escape command parameters. If that can be fixed it is better to use `exec` instead of `execRuntime`.
=> adding killEmulator function to kill specific emulator with AVD name.

lib/tools/adb-commands.js, lib/tools/system-calls.js, test/unit/adb-commands-specs.js
* Adjust reading of the process id with a given name to also make it work on Android 7 by using a combination of "ps" and "grep" commands because the api of "ps" has changed
* If an adb exec command fails, pass the stderr or the stdout (if possible) to the caller (because failing adb exec commands on Android 7 may throw an exception while on Android 6 they did not; instead, on Android 6 the exception text was returned in stdout)
=> Fixed issues with Android 7 (issue #6665 in Appium)

lib/tools/adb-commands.js, lib/tools/apk-utils.js, lib/tools/system-calls.js, test/unit/adb-commands-specs.js
adb seems to have gotten worse.
The only problem I'm still seeing is with `adb stop`, which now requires root access but when adb is run with root it does nothing. So rebooting is messed up.
=> Fix many problems for Nougat

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Use `-g` to grant all the permissions from the manifest, upon install.
Addresses https://github.com/appium/appium/issues/6928 and https://github.com/appium/appium/issues/6091
=> Grant permissions on install

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
The work done to add the `-g` flag to install breaks more than it fixes (which seems to be nothing).
=> Remove -g from install, which breaks stuff

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
Rather than getting processes by name, which does not work on recent systems, get all the processes and then sort through them for name. There are never _that_ many processes that this is onerous.
Fixes #177
=> Use all processes when looking for pids

.travis.yml, lib/tools/system-calls.js
We are returning the stderr instead of throwing errors, so some classes of errors are just swallowed without any indication. (This happens, for instance, when trying to stop a device at API level 25).
=> Stop swallowing errors in adb exec

lib/tools/android-manifest.js, lib/tools/apk-utils.js
PR https://github.com/appium/appium-adb/pull/186 not working with some applications.
Issue: #https://github.com/appium/appium/issues/7349, #https://github.com/appium/appium/issues/7353
- Granting permissions at run time works only when both below 2 cases matched
1.  Device API should be 23 and above (From device point of view)
2.  Application's `targetSdkVersion` version should be 23 and above (From Application point of view)
But there is no direct way to fetch `targetSdkVersion` from application's APK. Here we are relying on dumping apk info using (`aapt dump badging APK`). But unfortunately in legacy applications we do not find targetSdkVersion info. 
Till we find the better alternatives to figure out `targetSdkVersion`, removing the `targetSdkVersion` to grant permissions.
cc: @jlipps, …
=> refactored targetSdkVersionFromManifest 

lib/tools/system-calls.js, test/unit/syscalls-specs.js
Handle a new case that there is a message "adb server version (32) doesn't match this client (36); killing..." when the running adb doesn't match the appium-adb.
Ex:
adb.exe devices
List of devices attached
adb server version (32) doesn't match this client (36); killing...
\* daemon started successfully \*
0816f3699208ee6d        device
=> Correct the getConnectedDevices function

lib/tools/apk-utils.js, test/functional/apk-utils-e2e-specs.js, test/unit/apk-utils-specs.js
There is no discernible reason to exclude third-party apps from the check. Resolves https://github.com/appium/appium/issues/5538
=> Remove third-party restriction from app installed check

lib/tools/adb-commands.js
Throw a useful error, rather than an error about `0` not being a property of undefined, when there is no match (which seems to happen on Android 5.1).
=> Be a little more defensive around permissions checking

lib/helpers.js, lib/tools/apk-utils.js, test/functional/apk-utils-e2e-specs.js, test/unit/apk-utils-specs.js, test/unit/helper-specs.js
Fixes appium/appium#7607
When an app contains multiple activities, it's difficult to target correct activity names.
This PR adds an ability to set appWaitActivity value containing wildcards.
=> Enable to set a wildcard value in appWaitActivity.

lib/tools/system-calls.js
When I want to E2E test Android app with Google Play Services, appium-adb can't recognize AVD with Google API, test failed.
checkAvdExist `android list avd -c` command does not return AVD list with Google API.
So I change 'android list avd -c' to 'emulator -list-avds'.
=> Change 'get AVD list command' in systemCallMethods.checkAvdExist

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
This should speed up granting permissions for apps, since not all permissions should be granted explicitly. Some of them are considered as "normal" and are granted by default. See https://developer.android.com/guide/topics/permissions/requesting.html#normal-dangerous for more details.
=> Fix getting non-granted permissions

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
The currently present _install_ method is unable to properly upgrade a package if an older version is already installed
=> Add installOrUpgrade method to improve utilities setup

lib/adb.js
Fixes the case when package activity name cannot be extracted from manifest file. See https://github.com/appium/appium/issues/8221 for more details.
=> Set the default temp folder path

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
Add a method to set proxy settings via adb for the emulators, the idea is user can set proxy settings in the capabilities so they can use tunnels. They will also have to add the `--http-proxy` param in `avdArgs`.
=> Add proxy settings

lib/tools/android-manifest.js
the current one "Path must be a string. Received null" is not very descriptive.
=> Show better error description in case package name cannot be parsed from aapt output

lib/tools/system-calls.js
Otherwise the log gets muddied because the `adb unroot` will fail.
=> Only try to unroot adbd if it was rooted to begin with

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
...by escaping the dollar sign in the activity name. 
This was an issue for me as my app has the accept overlay dialog on start up, which is specified as the inner class com.android.settings.Settings$AppDrawOverlaySettingsActivity . The fix is just extending the regex set up to escape dollars, so they can be included in the activity name.
=> Support activities that are inner classes

README.md, docs/COMMANDS.md, lib/tools/system-calls.js, test/unit/syscalls-specs.js
Add a method to get adb version. Newer versions of adb added a lot of methods for emulators so in order to use those methods we should verify a minimum version of adb. This can also help us in the future to deprecate old version of adb to use with appium.
=> Add getAdbVersion method

lib/tools/adb-emu-commands.js, test/unit/adb-emu-commands-specs.js
We can rotate the emulators using `adb emu rotate` command, i'm adding this method here so we can call it later from base android drivers.
=> Add method to rotate emulators

lib/tools/apk-utils.js, test/functional/apk-utils-e2e-specs.js, test/unit/apk-utils-specs.js
Hopefully fixing appium/appium#8359 (more details there), whereby you can't specify an inner class as the start activity, because every thing from the dollar onwards gets clipped. Fix is just to escape the dollar (awfully similar to my last PR!)
=> Support start activities that contain an inner class

README.md, docs/COMMANDS.md, lib/tools/adb-emu-commands.js, test/unit/adb-emu-commands-specs.js
Add GSM methods supported by emulators
* gsmCall
* gsmSignal
* gsmVoice
with this methods we can emulate phone calls, change the signal strength and the state of the gprs connection.
=> Add emulator gsm methods

README.md, docs/COMMANDS.md, lib/tools/adb-emu-commands.js, test/unit/adb-emu-commands-specs.js
Add methods to change power in emulators
* _powerAC_ sets the state of the battery charger to connected or not
* _powerCapacity_ sets the battery percentage
* _powerOFF_ drains the battery so the emulator turns off. Another way of killing the emulator besides `adb emu kill`
=> Add emulator power methods

lib/tools/system-calls.js
The newest android sdk have separated the emulator cli from tools, so we should check if this is available under the own emulator folder before checking on tools.
=> use newest sdk emulator cli

README.md, docs/COMMANDS.md, lib/tools/system-calls.js, test/unit/syscalls-specs.js
Move `root`, `unroot` into their own methods so we can call them before running _adb shell_ commands that need to be root.
=> move root, unroot into their own methods

lib/tools/system-calls.js, test/unit/syscalls-specs.js
When adb is started on a different host/port `getConnectedDevices` will fail.
Now it should be fixed
=> Pass default arguments to adb devices

lib/tools/system-calls.js
Hey guys I've been playing around with avdArgs and I notice that when I put a wrong param the avd fail to launch with for ex. `unknown option --no-window` but the script continues without caring if the process exited with 1. Why are we waiting for the retry to throw an exception and not doing it immediately ? Is this a good approach to exit when the avd fails to launch ?
=> throw error on avd failing to launch

lib/tools/system-calls.js
Sometimes the `root` command fails but doesn't error out. So check the output to get the logging right.
=> Handle error from running as root

lib/tools/system-calls.js, test/unit/syscalls-specs.js
Different versions of Android apparently have different formats of `ls -la` output, so reduce the regexp to checking file size and date, which appear to always be next to each other.
In regard to https://github.com/appium/appium/issues/8800
=> Simplify filesize regexp

.travis.yml, lib/helpers.js, lib/tools/android-manifest.js, package.json, test/functional/helpers-specs-e2e-specs.js, test/unit/android-manifest-specs.js, test/unit/helper-specs.js
Rather than returning `null`, which causes the calling code to fail, return an object whose properties are null.
Also fix the tests, since setting `process.env.ANDROID_HOME` to `null` is the wrong technique (from the [docs](https://nodejs.org/api/process.html#process_process_env): "Assigning a property on process.env will implicitly convert the value to a string.").
=> Fix return value on getAndroidPlatformAndPath

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js, test/unit/apk-utils-specs.js
On Android O(api 26) i'm seeing setprop is failing is adb is not root. I modified setDeviceProperty method to set root, unroot in order to use setprop.
=> Set root, unroot for api 26

.travis.yml, lib/logcat.js, package.json, test/unit/logcat-specs.js
Currently, if `adb logcat` fails with a startup error like "execvp", we reject the promise and throw in the calling code. But if startup fails for any other reason we do nothing, and the promise is never resolved or rejected, so the session hangs.
So, keep track of whether we've started, so that we can log that it failed in this condition, and resolve the promise. Things will work fine but there will be no logcat capture.
Should fix https://github.com/appium/appium/issues/8743
=> Make sure adb logcat resolves

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
We can ensure gps toggle for emulators by calling adb with `adb shell settings put secure location_providers_allowed +gps`(tested on 4.4+). 
The idea is to change how we toggle gps specifically for emulators and also add a capability to enable/disable gps before launching an app.
=> Add method to get/set gps location provider

lib/tools/system-calls.js
Split multi-line avd output and log on individual lines.
At the moment we get logging like (see [this log](https://gist.github.com/vmaxim/79c608c0fc15ad9928fe7bd293f89648#file-appium_logs_2017-08-09-L83-L86)):
```
2017-08-09 05:58:57:293 - [ADB] [AVD OUTPUT] Hax is enabled
Hax ram_size 0x40000000
HAX is working and emulator runs in fast virt mode.
```
This PR will change it to:
```
2017-08-09 05:58:57:293 - [ADB] [AVD OUTPUT] Hax is enabled
2017-08-09 05:58:57:293 - [ADB] [AVD OUTPUT] Hax ram_size 0x40000000
2017-08-09 05:58:57:293 - [ADB] [AVD OUTPUT] HAX is working and emulator runs in fast virt mode.
```
=> Clean up logging of avd output

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
This will hopefully address issues like https://github.com/appium/appium/issues/9132
=> Set receiver names explicitly for the case Appium Settings app is not running

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
Update receiver names, otherwise switching WiFi/Data state won't work properly
=> Match receiver names to Appium Settings v 2.3.0+

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Add flag to make `installOrUpgrade` force uninstall and then install. This is needed for some cases of the settings app. In that case, we don't care about whether we save any state or data.
=> Add option to full reinstall on upgrade

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Rather than uninstall _a priori_, rely on uninstalling if there is an error in installing.
This means we don't need the `forceUninstall` parameter. This is technically a breaking change, but there is only one place where this method is used, so we can just fix that when the time comes.
=> Rely on failure to uninstall app

lib/tools/adb-commands.js, lib/tools/adb-emu-commands.js, test/functional/adb-emu-commands-e2e-specs.js, test/functional/setup.js, test/functional/syscalls-e2e-specs.js, test/unit/adb-commands-specs.js, test/unit/apk-utils-specs.js
I see that in many places people wrongly consider the returned value of getApiLevel is an integer number and perform string-to-number comparison, which never works properly (though throws no warnings/errors with JS). This PR unifies the stuff and makes the method to always return a number. The change should not be a problem for client libs, since `parseInt(x, 10)` will work properly if x is already an integer.
=> Make getApiLevel to return number instead of string

lib/tools/apk-utils.js
... so we can use URIs with multiple query parameters.
=> Escape ampersand in URIs

test/unit/helper-specs.js
The previous approach was not very good as for a unit test, because it is not going to restore previously changed ANDROID_HOME variable if the test fails.
=> Fix restoration of ANDROID_HOME env variable

test/unit/helper-specs.js, test/unit/logcat-specs.js, test/unit/syscalls-specs.js
Undo the skipping of the tests done in https://github.com/appium/appium-adb/pull/272 which never should have been merged.
In general, massive quarantining of tests is the **wrong way to go about things**. This means that all subsequent commits were not tested. In this case it was _one_ unit test that was the cause of all the rest failing, and relatively little work was needed to figure that out and get to a solution.
=> Stop skipping tests

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
ref: https://github.com/appium/appium-android-driver/commit/7094439c7ba19a533f7e3fcd446d35f2e4fb9009#diff-97eeab6ebf462ba97a11ee0221ddaf13R102
I've implemented check current locale method in `appium-adb`.
After merging this method, I'll call `ensureCurrentLocale` from `appium-android-driver`'s `ensureDeviceLocale` method.
=> Add ensure current locale

lib/logcat.js
Currently logcat output is pushed into two arrays, which causes extra memory consumption. The fix only pushes the data into single buffer and remembers its recent index. Also, the maximum size of the buffer is limited to 10k.
See https://github.com/appium/appium/issues/9727 for more details.
=> Optimize logcat output collection

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
When I fixing https://github.com/appium/appium-uiautomator2-driver/pull/115/files, I found the following use case for API 22-.
```
await androidHelpers.ensureDeviceLocale(adb, null, initialLocale);
```
In this PR, I put control flows for the issue as same as `setDeviceLanguageCountry`.
After merging this PR, I'll publish new updating patch version.
=> fix error case for api level 22-

lib/tools/android-manifest.js
When apk file is corrupted, `await exec(this.binaries.aapt, args);` line throws exception and appium-adb just says like `Error: packageAndLaunchActivityFromManifest failed. Original error: Command '***/aapt dump badging ***.apk' exited with code 1` without any problem details.
Of course the users can easily know more detailed message just running `***/aapt dump badging ***.apk` by themselves, but most users report this problem without doing so. (Actually my client sent me this error message without  aapt error detail)
So I want to include the std error detail to the error message to reduce the trouble shooting communication cost.
=> Improve logging for packageAndLaunchActivityFromManifest

lib/helpers.js, lib/tools/system-calls.js, package.json, test/unit/helper-specs.js
Addresses issues similar to https://github.com/appium/appium/issues/9926 where build-tools folder name might not match to the common naming pattern.
=> Sort build-tools subfolders by modification time rather than by name

lib/tools/apk-utils.js
There are often failures in setting the language/locale after the fact, because adb gets disconnected (see https://github.com/appium/appium/issues/9987).
So add a retry if there is a failure, after restarting adb.
=> Add retry to ensureCurrentLocale

package.json, test/adb-specs.js, test/functional/adb-commands-e2e-specs.js, test/functional/adb-e2e-specs.js, test/functional/adb-emu-commands-e2e-specs.js, test/functional/android-manifest-e2e-specs.js, test/functional/apk-signing-e2e-specs.js, test/functional/apk-utils-e2e-specs.js, test/functional/helpers-specs-e2e-specs.js, test/functional/logcat-e2e-specs.js, test/functional/syscalls-e2e-specs.js, test/unit/adb-commands-specs.js, test/unit/adb-emu-commands-specs.js, test/unit/android-manifest-specs.js, test/unit/apk-signing-specs.js, test/unit/apk-utils-specs.js, test/unit/helper-specs.js, test/unit/syscalls-specs.js
Add a gulp task for fixing eslint. And fix the arrow functions in mocha.
=> Get rid of arrow functions in mocha aparatus

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Granting permissions with `pm grant` takes quite a lot of time, however `adb install` utility has -g command line  argument, which allows to do it much faster and also does not require us to parse the  package info. This PR changes public method interface, so the module should become a higher major version number after it is merged.
=> Extend apk installation options

lib/tools/apk-utils.js
This should fix functional tests for https://github.com/appium/appium-android-driver/pull/319
=> Ignore grantPermissions option on install for Android API level older than 23

lib/tools/apk-utils.js
Sometimes this bloody tool fails to do what it is supposed to do, and the return code is still zero and the error description is printed into stdout instead of stderr.
=> Log the output of `adb install` command

lib/tools/apk-utils.js, package.json, test/unit/apk-utils-specs.js
I see there are packages where versionCode is not maintained properly (for example UIA2) and only versionName is updated. This PR adds version names comparison to address such things
=> Tune upgrade verification logic

lib/helpers.js, test/unit/helper-specs.js
I see that most of the users have these folder named properly. So lets have the fallback there, which makes the sorting operation safe for everyone.
=> Sort build-tools folders semantically by default

lib/tools/system-calls.js
The current implementation only works if `avdArgs` is of string type
=> Properly handle avdArgs if these are of type array

lib/tools/apk-utils.js
`adb install` still returns zero code even if installations fails, so we 'manually' check the stdout and throw the error if necessary
=> Fix `adb install` output handling

lib/tools/apk-signing.js, test/unit/apk-signing-specs.js
It turns out that verify.jar checks whether the default Appium certificate is present on the APK and not just any valid certificate.
=> Check whether the default certificate is present instead of just any certificate

lib/tools/apk-signing.js
zipalign might return non-zero code if the apk is already aligned. The previous implementation was erroneously treating such exception as apksigner utility absence.
Addresses https://github.com/appium/appium/issues/8945#issuecomment-374546182
=> Fix zipalign usage in case if apksigner utility is present on the local FS

lib/tools/apk-utils.js
* `waitForActivityOrNot` waits for the focused package and activity to be the package and activity specified in caps
* It is not always the case if an activity starts with '.', it is a fully qualified activity name (e.g.: https://github.com/aosp-mirror/platform_development/blob/master/samples/ApiDemos/AndroidManifest.xml#L66 the `android:name` does not start with a '.' and is not fully qualified)
* This case came up when we started using `apkAnalyzer` to parse activity names
* The fix is to add `${pkg}.${oneActivity}` as a _possible_ activity name that we can test
* For example, if the activity is 'ApiDemos' then we will look for either /^ApiDemos$/ or /^io.appium.android.apis.ApiDemos$/ as possible
(related to https://github.com/appium/appium/issues/10381)
=> Include pkg + activity as possible activity

lib/tools/system-calls.js, package.json
Instead of logging ADB exec commands like this: 
```Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","pm","clear","io.appium.settings"]```
...log them like this: 
```Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm clear io.appium.settings'```
...so that we can copy the commands and run them from command line directly for troubleshooting/testing purposes.
=> Show raw adb command instead of array of args

lib/tools/apk-utils.js, test/functional/adb-e2e-specs.js, test/functional/android-manifest-e2e-specs.js, test/unit/apk-utils-specs.js
* I need this for another PR because starters was unsuccessfully starting activities but was still returning zero as the error code so I need a way to check that 
(related PR: https://github.com/appium/appium-uiautomator2-driver/pull/151)
=> Throw errors if result of `startUri` has errors

lib/helpers.js, lib/tools/adb-commands.js, lib/tools/adb-emu-commands.js, lib/tools/android-manifest.js, lib/tools/apk-signing.js, lib/tools/apk-utils.js, lib/tools/system-calls.js, test/unit/adb-commands-specs.js
logAndThrow leaves unnecessary traces in logs, which confuse users when these are ignored in the caller code.
=> Replace `logAndThrow` with `throw new Error`

lib/tools/adb-commands.js, lib/tools/system-calls.js, test/unit/adb-commands-specs.js
Running any `svc` command, that changes device state, in non-root mode on Android emulator since API 23 has no effect.
@SrinivasanTarget FYI
=> Make sure adb is running in root mode before sending svc commands

lib/tools/apk-signing.js
Now I'm investigating unexpected Java9 signing problem on my PC, but warning error message just says `exited with code 1` and its information is too little to know the error cause.
To know the cause of such problem more easily, I'd like to improve the logging.
=> Improve warning error message

lib/tools/adb-commands.js
This will allow to avoid unexpected memory leaks
=> Add a method to remove the previously assigned logcat listener

lib/tools/apk-signing.js
It looks like apksigner utility has been fixed in the newer Android SDKs, so it is not necessary to patch it anymore.
=> Only patch apksigner if there is execution failure

lib/tools/adb-commands.js
Commands mentioned in https://github.com/appium/io.appium.settings/pull/15
Android P emulator returns 27 as the emulator's API level.
Thus, we can't filter if we send this command or not from API Level...
=> add hide api policy settings for Android P

lib/tools/adb-commands.js
I assume it would be smarter to wrap this command here up for further usage in https://github.com/appium/appium-android-driver/pull/399
=> Add screenrecord to adb commands

lib/tools/adb-commands.js
Selenium API also requires `altitude` value to set. The PR depends on https://github.com/appium/io.appium.settings/pull/17
=> Add parsing of altitude value

lib/tools/apk-signing.js
There is no point to perform zip align on already aligned package. This also saves resources.
=> Verify APK state before zipaligning it

lib/tools/apk-signing.js
Sometimes the utility is too talkative and spams the log with unnecessary stuff:
```
2018-09-21 17:37:40:644 - info: [debug] [ADB] WARNING: META-INF/android.arch.core_runtime.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2018-09-21 17:37:40:644 - info: [debug] [ADB] WARNING: META-INF/android.arch.lifecycle_extensions.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
2018-09-21 17:37:40:644 - info: [debug] [ADB] WARNING: META-INF/android.arch.lifecycle_livedata-core.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the …
```
=> Do not include apksigner warnings into the common log

lib/tools/adb-commands.js
This method is:
- slow
- not used anywhere
- duplicate of `targetSdkVersionUsingPKG`
=> Delete the unused method

lib/helpers.js, lib/tools/adb-commands.js, lib/tools/android-manifest.js, test/unit/adb-commands-specs.js
The idea behind this is the same as for https://github.com/appium/appium-adb/pull/355
Package manager invocation is more expensive from performance perspective in comparison to dumpsys call
=> Speed up permissions detection

.travis.yml, lib/tools/adb-commands.js, lib/tools/apk-utils.js, test/functional/adb-commands-e2e-specs.js, test/functional/adb-emu-commands-e2e-specs.js, test/functional/android-manifest-e2e-specs.js, test/functional/apk-utils-e2e-specs.js, test/functional/syscalls-e2e-specs.js, test/unit/adb-commands-specs.js, test/unit/apk-utils-specs.js
android 5 is missing some functional features we need to test
=> Update CI config to include Android 7 (API 24)

lib/tools/apk-signing.js
If `apksigner` is not there, we successfully make use of `verify.jar` to do certificate verification. But if it _is_ there, but fails, we also want to drop back to the older technology. This happens consistently, for instance, when Appium is running with Java 7 and the app was compiled with Java 8. In that case currently we _always_ assume it is unsigned and go through the whole signing process.
Also, there is no need to log stack traces into third party tools. So skip the stack trace for `apksigner` error logs.
Cc: @vrunoa
=> Make sure we try verify.jar if apksigner fails to verify

lib/helpers.js, lib/tools/adb-commands.js, lib/tools/android-manifest.js, lib/tools/apk-signing.js, lib/tools/apk-utils.js, lib/tools/apks-utils.js, lib/tools/index.js, package.json, test/functional/helpers-specs-e2e-specs.js, test/unit/apk-utils-specs.js
This PR continues what was started by @KazuCocoa  in https://github.com/appium/appium-adb/pull/366
the main idea behind the current implementation is to introduce .apks format support without making additional changes in the depending driver modules (aka it should simply work).
=> Introduce apks support

lib/tools/system-calls.js, package.json
In Android O emulators reboot it's failing due to root issues. 
```bash
Error: Error executing adbExec. Original error: 'Command '/mnt/android/android-sdk-linux/platform-tools/adb -P 5037 shell start' exited with code 1'; Stderr: 'start: must be root'; Code: '1'
Error: Error executing adbExec. Original error: 'Command '/mnt/android/android-sdk-linux/platform-tools/adb -P 5037 shell start' exited with code 1'; Stderr: 'start: must be root'; Code: '1'
2018/11/06 16:43:53 ui:     at ADB.execFunc$ (/tmp/chromeInstaller/node_modules/appium-adb/lib/tools/system-calls.js:317:13)
```
Adding root before calling shell starts fixes the issue.
=> Fix reboot for Android O

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Currently, Appium tries to reboot devices when a user change locale since Appium change locales via adb command for API level 23- devices. It doesn't work for real devices without root permission.
We don't need to reboot devices if we change them through  `io.appium.setting` while we need to set `language` and `locale` in caps so far. <= breaking change. (We can keep previous spec if we update io.appium.settings)
I ensured this works on Android 4.2(api level 17) and 6.0(api level 23) real devices.
Below log is an example to change locale via `persist.sys.locale` (but it does not work)
```
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s CB5A22LZ79 shell appops set io.appium.settings android\:mock_location allow'
[debug] [ADB] Device API level: 23 …
```
=> simplify changing locale

lib/tools/system-calls.js
Currently the code comment for `restartAdb` is incorrect. It says that `restartAdb` restarts the adb server _if_ `suppressKillServer` is true. The actual behavior is the opposite, though. `restartAdb` restarts the adb server _unless_ `suppressKillServer` is true. This PR simply changes the comment.
=> Correct comment for restartAdb

lib/tools/apk-signing.js, test/unit/apk-signing-specs.js
It looks like on *nix systems the workaround does not work as expected and the binary is not found even if `cwd` is set. See https://travis-ci.org/appium/appium-espresso-driver/jobs/457348839 for more details. 
So we only perform patching on Windows now
=> Only patch apksigner path on Windows

.travis.yml
Clean out the `sudo` and `dist` portions of the Travis config, in preparation for [upcoming changes to defaults](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) in Travis's Linux infrastructure.
=> Update dist in travis

.gitignore, lib/tools/adb-commands.js, lib/tools/apk-utils.js, test/functional/adb-commands-e2e-specs.js, test/unit/adb-commands-specs.js, test/unit/apk-utils-specs.js
closes #380 
We no longer need adb-county/language commands since we currently use io.appium.setting based locale handler.
=> Remove set language and country by persist

README.md, lib/tools/adb-commands.js, lib/tools/system-calls.js, test/functional/adb-commands-e2e-specs.js, test/unit/adb-commands-specs.js
According to the platform documentation the pidof utility should be available on all devices since API 23. Older devices might have it or might have not. In such case we fallback to the previous ps-based PID detection method.
Partially addresses https://github.com/appium/appium-adb/issues/395
=> Use pidof utility for process id detection

lib/tools/system-calls.js, test/functional/apk-utils-e2e-specs.js, test/functional/setup.js
After some discussion with @mykola-mokhnach we decided to try to retry _only_ when in the special cases of a protocol or device not found error.
No one knows why exactly the `retry` is necessary. If things get flakey it can be returned and noted.
=> Only retry adbExec if it is a protocol or device not found error

lib/tools/adb-commands.js
In the normal course of the logs we get the line for API level a number of times, even though the function is memoized. This is wasteful and also makes it seem like we're actually computing it each time.
=> Only print out API level once

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
pgrep is in priority, since pidof has been reported of having bugs on some platforms. It sometimes returns a big list of ids, which includes the ones for already terminated instances of the queried process.
=> Prefer pgrep over pidof for process id detection

lib/adb.js
Related to https://github.com/appium/appium-android-driver/pull/491
=> Remove the unused javaVersion option

README.md, lib/tools/adb-commands.js, test/functional/adb-commands-e2e-specs.js, test/unit/adb-commands-specs.js
Added methods for `adb reverse`, a command similar to `adb forward` that lets you reverse a socket connection.
=> Add methods for `adb reverse`

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
There is no point in having a separate default value for uninstallApk
=> Use the default adbExecTimeout value for uninstall

lib/adb.js, lib/helpers.js, lib/tools/apk-utils.js, lib/tools/apks-utils.js, lib/tools/system-calls.js
`adbExecTimeout` should have priority over the installation default timeouts if it is set to non-default value
=> Respect adbExecTimeout for apk(s) install

lib/adb.js, lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Normal call of `adb install` internally uploads the apk to the remote fs, executes `pm install` on it and then deleted the apk (see https://android.googlesource.com/platform/tools/base/+/master/ddmlib/src/main/java/com/android/ddmlib/Device.java#879). With Appium, though, it is usually necessary to reinstall a package multiple times and uploading it to the device for each install is time-consuming, especially for bigger APKs. This  PR automatically puts an APK into the internal cache, which can contain up to 10 items in order to save time for upload. In case the size of the remote cache reaches the size limit the algorithm will clean out the outdated items.
=> Introduce apk caching

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Android API 28 does not align each file in ls output into a separate row (`-1` option is needed for that). Although the older APIs don't support such option at all and return an error if it is provided. This PR tries to properly handle both cases
=> Properly handle ls attributes presence for different API levels

lib/tools/apk-utils.js
Sometimes it might be needed to disable caching (for example in cloud, where devices are reset automatically after each test)
=> Only apply caching if remoteAppsCacheLimit is greater than zero

lib/tools/apk-utils.js
Under some circumstances it is possible that the previous algorithm could remove less expired items than it should be removed.
=> Tune cache cleanup algorithm

lib/tools/apk-utils.js, lib/tools/apks-utils.js, lib/tools/system-calls.js, test/unit/apk-utils-specs.js
Object.assign is sometimes not exactly we'd like to use for setting the default values. For example:
```js
d = _.defaults({a: 1}, {b:2}, {c:undefined, a:undefined});
JSON.stringify(d) //{ "a":1,"b":2}
```
```js
d = Object.assign({a: 1}, {b:2}, {c:undefined, a:undefined});
JSON.stringify(d) //{ "a":1undefined, "b":2, "c": undefined}
```
Addresses https://github.com/appium/appium/issues/12409
=> Fix setting of default values

lib/tools/adb-commands.js, test/functional/adb-commands-e2e-specs.js
`pushFile` isn't working on some later versions of Android SDK. 
Was getting error `remote secure_mkdirs failed: Operation not permitted`. Workaround is to create the directory first using `adb shell mkdir` before pushing the file. That directory will have the correct permissions.
(another issue that had this problem: https://github.com/bazelbuild/examples/issues/77)
=> Create directory before push to avoid permission issue

lib/helpers.js, lib/tools/adb-commands.js, lib/tools/apk-utils.js, test/functional/apk-utils-e2e-specs.js, test/unit/apk-utils-specs.js
As of Android SDK 29 (Android Q), this apk (com.google.android.permissioncontroller) opens prior to the AUT opening to prompt the user which permissions to allow. 
https://user-images.githubusercontent.com/852574/54451599-6faa6e80-4710-11e9-8917-95126af79e79.png
^ This breaks tests and makes the AUT not start.
The way around this (what this PR does) is automatically grants all permissions for SDK level 29+ on install. Automatically granting this permission makes it bypass this APK.
This would be a breaking change though, so I'd like other opinions.
The choices are
1. Always grant permissions automatically, thus deprecating `autoGrantPermissions` capability. Add a new capability, something like `revokePermissions`, which takes an array of permissions and revokes them after app is started …
=> Change 'windows' to 'displays'

.travis.yml
Get rid of hard-coded versions of things, and remove superfluous `ANDROID_` from environment variable names.
=> Clean up Travis config

.gitignore, ci-jobs/templates/android-e2e-template.yml, lib/tools/adb-commands.js, lib/tools/system-calls.js, test/functional/adb-commands-e2e-specs.js, test/functional/syscalls-e2e-specs.js, test/unit/adb-commands-specs.js, test/unit/syscalls-specs.js
This addresses two problems: `adb root/unroot` 1. works intermittently, 2. sometimes cases the device to go offline.
The fix is:
1. retries `root/unroot` instead of calling it just once
2. after a root/unroot occurs, check if there's no connected devices and if there aren't any, restart adb (uses a new method called `restartAdbIfDevicesOffline ()`
This PR also:
1. Uses mocha multireporters so that the logs show tests being called
2. Fixes an IME test that wasn't working
=> Fix: Restart ADB server when devices go offline

lib/tools/system-calls.js
The previous implementation was not properly handling the case where the other parallel exec command(s) is not exclusive.
=> Fix the exclusive exec behaviour

lib/tools/adb-emu-commands.js, test/unit/adb-emu-commands-specs.js
First step to adding support for setting sensor values on Android Emulators.
=> Add support for setting Sensors on Android Emulators

ci-jobs/nightly.yml, ci-jobs/scripts/start-emulator.sh, lib/tools/apk-utils.js, lib/tools/apks-utils.js, test/functional/setup.js, test/unit/android-manifest-specs.js, test/unit/apk-utils-specs.js
The idea is too add more visibility to the testers when adb fails to this by explicitly saying 
`Set allowTestPackages capability to true in order to allow test packages installation.` in the logs. 
Work in progress, I want to add another unit test to check this.
=> Warn install failed due to INSTALL_FAILED_TEST_ONLY

lib/tools/android-manifest.js
Apkanalyzer parse can give wrong launch activity name when more than MAIN and LAUNCHER activities exist and they have 'enabled' attribute.
case:
`<activity-alias>
... 
android:enabled='true'
...><MAIN> <LAUNCHER>
/>   
<activity-alias>
... 
android:enabled='false'
...><MAIN> <LAUNCHER>
/>`
To avoid this case, parser must check enabled tag of activity. Firstly, i checked whether 'enabled' attribute exists or not. If not exist, it is ok to take as launchable activity. If exist, i checked the whether 'enabled' is set to true or not.
=> modify apk analyzer query to find launch activity

README.md, lib/helpers.js, lib/tools/android-manifest.js, lib/tools/apk-utils.js, test/adb-specs.js, test/functional/android-manifest-e2e-specs.js, test/unit/android-manifest-specs.js, test/unit/helper-specs.js
Google has completely deprecated aapt tool since SDK 28 and removed it from build tools, so we need to start shifting to aapt2/apkanalyzer usage.
=> Prefer apkanalyzer for package information retrieval

lib/tools/adb-commands.js, lib/tools/android-manifest.js, lib/tools/apk-utils.js, package.json
The only method which is left (still uses the deprecated aapt) is the resources extractor
=> Update manifest helpers to use aapt2

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
According to https://github.com/appium/appium/issues/13567 the implementation of `pgrep` in Android 5 is buggy and should not be used.
=> fix: Always fall back to ps-based PID detection on Android 5 and older versions

lib/tools/adb-commands.js
The part of https://github.com/appium/appium/issues/13466 implementation
=> feat: Add a possibility to retrieve the clipboard content on Android 10

lib/tools/adb-commands.js
Fixes https://github.com/appium/appium-adb/pull/473#discussion_r347388767
=> fix: return the clipboard content as base64-encoded string

lib/tools/adb-commands.js
Addresses https://discuss.appium.io/t/unable-to-launch-an-already-installed-app-through-appium/28853
This error happens if application manifest contains permissions constants, which are only available for newer Android versions while being tested on older APIs
=> fix: Ignore 'Unknown permission' error for batch permission changes

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
It makes sense to update the timestamp of the cached file if the file has been reused, so it does not get deleted because its position in the sorted ls output would be too close to the bottom
=> chore: Bump the cached application time stamp if needed

.travis.yml, lib/helpers.js, lib/tools/apk-utils.js, test/functional/apk-utils-e2e-specs.js, test/unit/apk-utils-specs.js
Hi there,
I raised [an issue](https://github.com/appium/appium/issues/13628) around starting apps with just intents and I think currently it's not possible to launch an android app with just an intent in the desired capabilities; this PR should allow you to do that. I know it's possible to do it with a `mobile:deeplink` command at the moment, but if I want to run this against multiple configs where some can be launched directly with a pkg/activity, then I have to special case the code, and it would be great to keep that encapsulated in the desired capabilities.
I've just used what was already there, but changed the validation to allow you to call `startApp` with `intentAction` and `optionalIntentArgs` even when there isn't an activity provided. 
This works for me (though you do have to …
=> Allow starting an app with just intent

lib/tools/adb-commands.js, lib/tools/index.js, lib/tools/settings-client-commands.js
The `adb-cmmands` module has grown too big. It's time to make it less greedy
=> refactor: Move commands related to Settings App to the separate module

test/functional/apk-utils-e2e-specs.js
The tests have been failing because of this timeout.
=> fix: extend adb timeout on CI

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
`getPlatformVersion` returns 29 in Android R preview, although the version should be for Android Q.
In Android Q, the returned value became from 28 to 29 in middle or later beta. Thus, I predict R also will be 30, but for now, let's add a workaround the same as Android Q case for Android R preview.
=> feat: Return API Level 30 for Android R preview

lib/adb.js, lib/tools/system-calls.js, test/unit/syscalls-specs.js
Sometimes (as in the `appium-uiautomator2-driver` tests) the device is there but reported as `'offline'`, though fully interactive. It seems to be when another adb server is/was running on a different port.
I'm not sure of the implications for this, so defaulting to `false`.
=> feat: add allowOfflineDevices capability

lib/tools/adb-commands.js, lib/tools/apk-utils.js, test/functional/adb-commands-e2e-specs.js, test/unit/apk-utils-specs.js
Recently Google has added the support of streamed installs to adb. This type of installs does not require the apk file to be pushed to the device first, which allows to save time for the whole operation and to save space on SD card.
=> feat: Do not apply caching if the device under test supports streamed installs

lib/tools/apk-signing.js
UIA2 requires the application under test to be signed by any valid signature, not just the default one we use in Appium. this feature plus some improvements in UIA2 driver will allow to save session init time for already signed apps.
=> feat: Introduce signature verification options

lib/adb.js
Since `getApiLevel` is memoized once successful, this does not have performance impacts. Within the drivers we always get the API level directly after getting the ADB instance, so that will just be pre-populated.
This will necessitate some refactoring of https://github.com/appium/appium-uiautomator2-driver/pull/369
=> fix: make sure device is reachable in createADB

lib/adb.js
This reverts commit 0b029c4fd6132bcfb9b614f673eb8cb4653c6b74.
It turns out this patch will fail adb creation if multiple devices are connected to the same machine, because we sometimes should find out the actual udid of the device under test after adb instance is created by analyzing the `list` command output. Perhaps, it makes sense to move this patch into appium-android-driver's helpers, methods `createADB` and `getDeviceInfoFromCaps` after `setDeviceId` has been called.
=> Revert "fix: make sure device is reachable in createADB (#504)"

lib/helpers.js, lib/tools/apk-signing.js, lib/tools/system-calls.js, test/unit/apk-signing-specs.js
This will allow to simplify our client code and get rid of some ugly workarounds. Also, the execution speed should improve a bit
=> refactor: Switch apksigner to directly use the JAR implementation rather than the wrapper script

ci-jobs/ci.yml, ci-jobs/templates/android-e2e-template.yml
Got `##[error]This job was temporarily blocked because it uses a Microsoft hosted agent (MacOS-10.13) that will be permanently removed on March 23rd, 2020.  See https://aka.ms/blocked-hosted-agent for more information.` error in https://github.com/appium/appium-adb/pull/507/checks?check_run_id=498080242
=> chore: update to macOS 10.15

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
closes https://github.com/appium/appium-desktop/issues/1265
It looks some manufactures set limitations for hidden api policies.
We can ignore them when it fails because of such customisation with printing the error as info.
=> feat: ignore setting hidden api policies error

lib/helpers.js
The `glob` [documentation](https://www.npmjs.com/package/glob) says:
```
Windows
Please only use forward-slashes in glob expressions.
Though windows uses either / or \ as its path separator, only / characters are used by this glob implementation. You must use forward-slashes only in glob expressions. Back-slashes will always be interpreted as escape characters, not path separators.
Results from absolute patterns such as /foo/* are mounted onto the root setting using path.join. On windows, this will by default result in /foo/* matching C:\foo\bar.txt.
```
=> fix: Update glob expressions

lib/tools/adb-commands.js, package.json, test/unit/adb-commands-specs.js
This helper is needed for android-driver, which has the corresponding TODO marker: https://github.com/appium/appium-android-driver/blob/63f7e87110e6e89c70886dc9092802fcd64f5735/lib/webview-helpers.js#L159
=> feat: Add a helper to get process name for the given PID

lib/tools/adb-emu-commands.js, test/functional/adb-emu-commands-e2e-specs.js
Android Emulator console has a set of pretty handy features, like snapshotting, rotation, etc. There is no reason not to use them
=> feat: Add a possibility for emulator commands execution via telnet

lib/tools/adb-commands.js, lib/tools/android-manifest.js, lib/tools/apk-signing.js, lib/tools/system-calls.js, package.json
There is no need to explicitly import `shell-quote`, since it's already being exposed by appium-support module
=> chore: Use quote helper imported from appium-support

lib/helpers.js, lib/tools/apk-utils.js
It looks like Google has updated aapt2 commands spec since we checked that for the last time: https://developer.android.com/studio/command-line/aapt2
=> fix: Update aapt2 commands

lib/helpers.js, lib/tools/system-calls.js
BREAKING CHANGE: Moved all non-mandatory options into the single opts argument
=> refactor: Add a possibility to customize emulator env on startup

lib/logcat.js, lib/tools/adb-commands.js, lib/tools/system-calls.js, test/unit/logcat-specs.js
https://github.com/appium/appium/issues/14356
=> feat: Add a possibility to customize logcat filtering

lib/tools/system-calls.js
Noticed below commands were in `cmdline-tools` path for newer packages.
```
apkanalyzer
avdmanager
lint
screenshot2
sdkmanager
```
`latest` is the default one. (I mean other versions can select when 'show packages' is on. For now, it is only 1.0 though)
=> feat: add cmdline-tools path in binary search

index.js, lib/adb.js, lib/tools/index.js, lib/tools/system-calls.js
I want to call only `getAndroidBinaryPath` to resolve android related binaries in appium-doctor in https://github.com/appium/appium-doctor/pull/101
For it, would like to expose the method outside of ADB instance.
Is this PR correct way?
I tested this branch worked on the doctor and UIA2 on my local (with `link`)
=> feat: Expose get android binary path

lib/tools/adb-commands.js, lib/tools/apk-utils.js, lib/tools/system-calls.js, test/unit/syscalls-specs.js
Killing the whole adb server can sometimes corrupt other parallel tests that are running on the same machine and expect adb connection to be stable. The `reconnect` command affects only offline devices and does not touch other properly connected units, which is much more convenient for us from this perspective.
=> feat: Add reconnect command handler

README.md, docs/COMMANDS.md, lib/tools/adb-commands.js, lib/tools/apk-utils.js, lib/tools/system-calls.js, test/functional/adb-commands-e2e-specs.js, test/functional/syscalls-e2e-specs.js, test/unit/syscalls-specs.js
Google has recently added incremental install feature for ADB. It gets enabled automatically by default if the device under test supports it, however it is still not very stable and breaks server install: https://github.com/appium/appium/issues/14387
This PR adds an option to forcefully disable incremental installs, which is going to be used for server deployment.
=> feat: Add a possibility to disable incremental install

lib/tools/adb-commands.js
After some more source code analysis I've figured out more precise way to detect incremental install feature support (see `calculate_install_mode` method from `adb_install.cpp`).
=> fix: Update incremental install support detection

lib/tools/system-calls.js
The current code assumes that the user has installed the full Android build tools, which is probably true in the vast number of cases. However, if someone has installed a subset of the tools (for example, installing ADB.exe from https://androidstudio.io/downloads/tools/download-the-latest-version-of-adb.exe.html), then those tools could be in any folder location and are not necessarily constrained to the set of folders specified in SDK_BINARY_ROOTS.
This change simply allows someone to use sdkRoot to specify the full folder path to the tool in question. It's at the end of SDK_BINARY_ROOTS, so it will have no impact on users with the full build tools in place.
I also corrected a typo that I noticed while reading through the code.
=> feat: Allow sdkRoot to specify a full folder path

lib/tools/adb-commands.js
When I ran tests against emulator API Level 30 https://github.com/appium/ruby_lib_core/pull/268, only `@driver.execute_script 'mobile: performEditorAction', { action: 'normal' }` failed.
I ran the command on my local, then exactly it did not work because the IME was not enabled.
Emulators such as API Level 29 did not need call `enableIME` in the scenario.
It worked after I enabled the IME manually, but it's safe to calls `this.enableIME(ime);` here to keep the current behaviour of `runInImeContext`. I ran a couple of times with this PR style against different API emulators, but they had no issue. 
This increases adb call time, but it should not impact rather than the `runInImeContext` behaves differently.
=> fix: ensure the ime is enabled for API level 30

lib/tools/adb-emu-commands.js, lib/tools/system-calls.js, package.json, test/functional/adb-emu-commands-e2e-specs.js
https://github.com/appium/appium/issues/14347#issuecomment-670440234
=> chore: Only use -delay-adb emulator startup detection if image API version is above 27

lib/helpers.js, lib/tools/adb-emu-commands.js, lib/tools/apk-signing.js, lib/tools/system-calls.js, test/functional/adb-emu-commands-e2e-specs.js
It turns out that Google bumped minimum java version for its build tools, but forgot to do this for SDK tools, like avdmanager. This causes java version incompatibility errors while executing `avdmanager` script on systems where Java9+ is set in JAVA_HOME.
This PR removed usage of avdmanager and replaces it with NodeJS-based config reader, which is way faster and does not experience the above issues
=> refactor: Replace avdmanager usage with faster config reading primitives

lib/tools/adb-commands.js, lib/tools/system-calls.js, test/unit/adb-commands-specs.js
At some point of time Google has changed the default `ps` behaviour, so it only lists processes that belong to the current shell user rather to all users. It is necessary to execute ps with -A command line argument to mimic the previous behaviour.
Also related to https://github.com/appium/appium/issues/14709
=> fix: Update process lookup behaviour for newer Android versions

lib/tools/apk-signing.js
It looks like this strange tool may print error output into stdout instead of stderr
=> chore: Include stdout as well if apksigner fails

lib/tools/apk-signing.js
This is not needed anymore after sign.jar has been deprecated
=> chore: Remove the obsolete validation for zipalign

lib/helpers.js, lib/tools/adb-emu-commands.js
On Windows avds are stored, by default, in `C:\Users\{USER}\.android\avd`.
The current version of `listEmulators()` searches for the avd folder in `C:\Users\{USER}\AppData\Local\Android` (via `getAndroidPrefsRoot()`), but that's the wrong location.
> By default, the emulator stores configuration files under $HOME/.android/ and AVD data under $HOME/.android/avd/. You can override the defaults by setting the following environment variables. The emulator -avd <avd_name> command searches the avd directory in the order of the values in $ANDROID_AVD_HOME, $ANDROID_SDK_HOME/.android/avd/, and $HOME/.android/avd/.
Source: https://developer.android.com/studio/command-line/variables
=> fix: Android preferences root path on Windows

lib/helpers.js, lib/tools/apks-utils.js, test/unit/apk-utils-specs.js
Part of https://github.com/appium/appium/issues/14823#issuecomment-775729347
```
app installation (see also `adb shell cmd package help`):
install [-lrtsdg] [--instant] PACKAGE
push a single package to the device and install it
install-multiple [-lrtsdpg] [--instant] PACKAGE...
push multiple APKs to the device for a single package and install them
...
-r: replace existing application
-t: allow test packages
-d: allow version code downgrade (debuggable packages only)
-p: partial application install (install-multiple only)
-g: grant all runtime permissions
...
```
=> feat: expose install-multiple adb call

lib/tools/settings-client-commands.js
Enable applications that use location speed to mock properly mock locations from inside a test.
This is related to:
- **python-client** pull request: https://github.com/appium/python-client/pull/594
- **io.appium.settings** pull request https://github.com/appium/io.appium.settings/pull/70
=> feat: Added optional speed parameter to properly mock locations for android devices

lib/helpers.js, test/unit/helper-specs.js
I think we should relax locked screen condition logic for newer Android devices.
https://github.com/appium/appium-adb/blob/master/lib/tools/adb-commands.js#L615-L632
Newer Android devices (i tested a few real devices), lock screen is simply `NotificationShade` or `StatusBar` after keycode 62. But current our logic does not consider such case as locked screen. So, our `lock` never be succeeded.
When these app is focused, Appium can unlock them with https://github.com/appium/appium-android-driver/blob/9d120ba76df18ada8c5793af3d42f9b1aa4937cb/lib/android-helpers.js#L648-L679 , so I think we can consider `NotificationShade` and `StatusBar` as part of `isShowingLockscreen`.
(at least, an Android 7.1 real device had `mShowingLockscreen`. Haven't checked with android 8 and 9.)
=> feat: consider NotificationShade and StatusBar as lock screen for newer android versions

lib/helpers.js, test/unit/helper-specs.js
I assume there was a typo is in the code, because the screen is supposed to be locked if Keyguard is shown and vice versa.
=> fix: Update screen lock detection based on KeyguardStateMonitor

lib/helpers.js, lib/tools/adb-commands.js, lib/tools/apk-utils.js, lib/tools/settings-client-commands.js
It looks like the system `spawn` call does not always handle command line arguments the way we want them to be handled in Windows. This patch fixes it.
=> fix: Escape command line arguments for Windows

.gitignore, lib/tools/apk-signing.js, test/unit/apk-signing-specs.js
The `java.lang.Error: Properties init: Could not determine current working directory` error pops up randomly while checking app signature with apksigner and we are not quite sure why.  My guess - a race condition in java vm initialization. Nevertheless, lets make Appium to believe the file is already signed, because it would be true for 99% of UIAutomator2-based tests, where we presign server binaries while publishing their NPM module. If these are not signed, e.g. in case of Espresso, then the next step(s) would anyway fail.
See https://github.com/appium/appium/issues/14724 for more details.
=> chore: Assume cert validation succeeds if java vm error is thrown

lib/helpers.js
Related to https://github.com/appium/appium/issues/15693
=> refactor: Fetch java executable location from PATH if JAVA_HOME is unset

lib/tools/system-calls.js, test/functional/syscalls-e2e-specs.js, test/unit/syscalls-specs.js
[Issue 15696- appium-adb: no way to read stderr from shell commands that exit with code 0](https://github.com/appium/appium/issues/15696) describes a scenario in which appium-adb's `shell` command throws away `stderr` when a command exits with code 0. To add support for this scenario, this PR implements the following approach (as described by @dbjorge in the issue):
> A new `outputFormat` option to `shell`/`adbExec` that: 
> * accepts either `stdout` or `full`
> * defaults to `stdout`
> * is checked during the `adbExec` success path; if `stdout`, `adbExec` matches the existing behavior and returns `stdout`, and if `full`, `adbExec` instead returns the full original output from `await teen_process.exec(...)` (ie, an object with `stdout`, `stderr`, and `code` properties)
Comments on the …
=> feat: Add outputFormat option to shell command

lib/tools/adb-commands.js
Refactor pull command to accept options object while still keeping default timeout set to 60 seconds to ensure backwards compatibility.
Fixes issue [#15787](https://github.com/appium/appium/issues/15787)
=> feat: Add opts to pull command

lib/tools/system-calls.js
Sometimes adb prints error messages to stdout and keeps stderr empty. I don't know the reason of such behaviour (perhaps some legacy stuff)
=> chore: Tune error output of adbExec

lib/tools/aab-utils.js, lib/tools/apk-utils.js, lib/tools/apks-utils.js, lib/tools/index.js
I don't think we can easily add .apks support into Espresso driver, but we can still transform .aab files into .apk directly
=> feat: Add a helper to create a universal apk from an .aab bundle

lib/tools/system-calls.js, test/unit/syscalls-specs.js
This change adds the ability to use `adb devices -l` instead of plain `adb devices`. This lets addition information get read when obtaining connected devices.
The `-l` is short for "long" so I used the same naming when creating the options object.
https://developer.android.com/studio/command-line/adb#devicestatus
=> Add support for adb devices -l

lib/adb.js, test/functional/adb-e2e-specs.js, test/unit/adb-specs.js
Closes appium/appium#16932
Adds a `cloneADB` function that copies already initialized properties created in `ADB.createADB()`.
This was added in the top-level class since it uses the class constructor. It was attached directly to the class to avoid the prototype assignment warning.
=> Add cloneADB function

lib/tools/settings-client-commands.js, test/unit/adb-commands-specs.js
This commit changes to start setting mock locations as a foreground service for API versions 26+, according to [the README of io.appium.settings](https://github.com/appium/io.appium.settings/blob/master/README.md#setting-mock-locations).
=> feat: Start setting mock locations as a foreground service

lib/tools/adb-commands.js
Related to https://github.com/appium/appium/issues/17128
=> feat: Add an option to enforce dumpsys usage for launchable activity name detection

test/functional/adb-commands-e2e-specs.js, test/functional/adb-e2e-specs.js, test/functional/adb-emu-commands-e2e-specs.js, test/functional/android-manifest-e2e-specs.js, test/functional/apk-utils-e2e-specs.js, test/functional/syscalls-e2e-specs.js, test/unit/adb-commands-specs.js, test/unit/adb-emu-commands-specs.js, test/unit/adb-specs.js, test/unit/apk-signing-specs.js, test/unit/apk-utils-specs.js, test/unit/syscalls-specs.js
We should never import from index.js in tests, but rather directly from corresponding source modules.
=> tests: Fix ADB instance import

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
I ran into an interesting behavior. Passing a non-ascii character to the mobile:type command always succeeds the first time but fails the second time. The reason is that the regex object is stateful.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test
> JavaScript [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) objects are stateful when they have the [global](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global) or [sticky](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky) flags set
This PR fixes the problem by changing it to a local variable.
=> fix: escape doesn't work due to misuse of regex

lib/tools/system-calls.js
Addresses https://github.com/appium/appium/issues/18717
=> fix: Properly handle the situation where reboot_readiness check returns a non-zero exit code

.github/workflows/functional-test.yml
This PR adds API-32 to CI targets.
ref. https://github.com/appium/appium-uiautomator2-driver/pull/614#issuecomment-1572384137
=> ci: add api-32 to functional test targets

lib/tools/adb-emu-commands.js, test/unit/adb-emu-commands-specs.js
Let adb itself validate parameters format. We only make sure if these are not empty
=> fix: Streamline parameters validation for emulator commands

lib/adb.ts
if my understanding is correct, I think we need a `await` keyword, which is somehow dropped since https://github.com/appium/appium-adb/pull/661/
=> fix: insert a missing await keyword

lib/tools/adb-commands.js
Maybe it could help to people that get stuck with a cryptic error message while using Chinese phones to run their tests
=> chore: Add a troubleshooting link to the WRITE_SECURE_SETTINGS error message

index.ts, lib/adb.ts, lib/helpers.js, lib/mixins.ts, lib/options.ts, lib/tools/apk-signing.js, lib/tools/apks-utils.js, lib/tools/settings-client-commands.js, package.json
- fix `getApksignerForOs` return type
- move options interface into its own file
- export `ApkSigningCommands` interface and attach to `ADB`
- export everything in `apks-utils` module; fix return values
- fix types in `tools/apk-signing`
- use TS v5.0.x
=> feat(types): export more types

lib/tools/settings-client-commands.js, lib/tools/utf7.js, package.json
The https://www.npmjs.com/package/utf7 package has been released 7 years ago for the last time and thus has vulnerable dependencies:
```
node_modules/@babel/core/node_modules/semver
node_modules/@babel/helper-compilation-targets/node_modules/semver
node_modules/istanbul-lib-instrument/node_modules/semver
node_modules/make-dir/node_modules/semver
node_modules/npm-run-all/node_modules/semver
node_modules/read-pkg-up/node_modules/semver
node_modules/read-pkg/node_modules/semver
node_modules/utf7/node_modules/semver
utf7  >=1.0.2
Depends on vulnerable versions of semver
node_modules/utf7
appium-adb  >=7.20.0
Depends on vulnerable versions of utf7
node_modules/appium-adb
vm2  *
Severity: critical
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-cchq-frgv-rjh5
vm2 Sandbox …
```
=> fix: Move utf7 encoding primitives to the module codebase

lib/tools/adb-commands.js, lib/tools/settings-client-commands.js, test/unit/adb-commands-specs.js
It looks like a command below launches `io.appium.settings` process, which can be found by `[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s D0AA002182JC0202126 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'`, but the app was not started in the background properly (no the app in the notification). It causes io.appium.settings process did not start properly situation, thus for example `driver.location` to get the location/set location causes an error because the `io.appium.settings` was not started properly with `this.startApp`.
We must start the settings app forcefully once with `this.startApp` to start the settings app process properly.
```
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P …
```
=> feat: add isSettingsAppServiceRunningInForeground to check the settings' service existence better

lib/adb.ts
Related to https://github.com/appium/appium/issues/19940
=> fix: Do not call 'start-server' if the 'suppressKillServer' option is enabled

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
I've also updated the algorithm for installed app detection
=> fix: Do not check if app is installed if we know it is

lib/helpers.js, lib/tools/adb-commands.js, lib/tools/lockmgmt.js
Based on https://stackoverflow.com/questions/19611945/obtain-screen-status-using-adb
=> fix: Add one more condition to the lock state detection

lib/tools/system-calls.js
This service is always present on API 31+ emulators
=> chore: Always use reboot_readiness service to detect emulator startup  for API 31+

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
closes https://github.com/appium/appium-adb/issues/738
Then, eventually `mobile: isAppInstalled` will have `user` like startActivity.
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-isappinstalled`
```
$ adb -s emulator-5556 shell pm -h
Package manager (package) commands:
help
Print this help text.
path [--user USER_ID] PACKAGE
Print the path to the .apk of the given PACKAGE.
```
```
list packages [-f] [-d] [-e] [-s] [-3] [-i] [-l] [-u] [-U]
[--show-versioncode] [--apex-only] [--factory-only]
[--uid UID] [--user USER_ID] [FILTER]
Prints all packages; optionally only those whose name contains
the text in FILTER.  Options are:
-f: see their associated file
-a: all known packages (but excluding APEXes)
-d: filter to only show disabled packages
-e: filter to …
```
=> feat: let pass user for isAppInstalled

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
This settings command worked on Android 9, 10, 11, 12, 13 and 14 real devices, so I think at least this can be alternative of existing animation one. I haven't tested for older than API level 26. So for now, we could use this as https://github.com/appium/appium-espresso-driver/pull/1007
=> feat: enable window animation via settings

lib/logcat.js
Now it might not be a thing to use nanosecond timestamps as keys, but in the future, when CPUs are fast enough it might create issues that are hard to detect.
=> fix: Prefer indexes over timestamps as logcat keys

lib/logcat.js, package.json, test/unit/logcat-specs.js
It turns out the keys() method of LRUCache returns items ordered from most recently used to least used and the order for rkeys() is inverted.
=> fix: Fix recent entry retrieval

lib/tools/adb-commands.js, test/functional/adb-commands-e2e-specs.js
This method could be useful to select a free device port to start a server on. 
See https://gist.github.com/jkstill/5095725 for more details
=> feat: Add a method to list device ports

lib/helpers.js, test/unit/helper-specs.js
Related to https://github.com/appium/appium/issues/20730
=> chore: use start-activity for api level 26+

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
`startUri()` requires `pkg` argument as app package name but app package can be omitted on executing `am start`.
It may show disambiguation popup in some cases (e.g. when there are multiple apps which handle the given URI and the default app is not configured.)
=> fix: Make package argument of startUri optional

README.md
The import was missing curly braces, and it was importing the wrong thing which led to the example failing, as also described in https://github.com/appium/appium-adb/issues/649 that was closed by the author without sending a PR.
I thought the library code might have changed and/or the README had got out of sync, but after looking at the source I realised what was happening.
This little change helps people get started with the lib. Hope it helps!
=> docs: Update README so the example works verbatim

lib/helpers.js, lib/tools/lockmgmt.js, test/unit/helper-specs.js
To support https://github.com/appium/appium-uiautomator2-driver/issues/859 case.
I confirmed that the current method to detect the lock screen didn't work in the issue's use case. Actually, when the device screen was off while screen recording was working, the existing one didn't match as "locked."
`screenState=SCREEN_STATE_OFF` could help in this case.
This doesn't change current behavior when no screen recording is working, so this could be "fix" I think but this adds a new flag to detect the state so I made this as a "feat."
=> feat: add screenState=SCREEN_STATE_OFF as the screen locked

lib/helpers.js, package.json
BREAKING CHANGE: Required Node.js version has been bumped to ^20.19.0 || ^22.12.0 || >=24.0.0
BREAKING CHANGE: Required npm version has been bumped to >=10
=> feat: Bump Node.js version

lib/tools/app-commands.js
Add the activity name for cases the activity fully qualified name is with a different package name. For example: `com.android.chrome/com.google.android.apps.chrome.Main`.
**Appium log:**
```
[HTTP] --> POST /session {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:automationName":"uiautomator2","appium:appPackage":"com.android.chrome","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}}
[AppiumDriver@29b2] Calling AppiumDriver.createSession() with args: [{"alwaysMatch":{"platformName":"Android","appium:automationName":"uiautomator2","appium:appPackage":"com.android.chrome","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTime …
```
=> fix: Add activity name for cases the activity fully qualified name is with a different package name
