appium/appium-adb

lib/adb.js, test/unit/binary-path-specs.js
Created a factory method to consolidate instantiation with checking adb exists.
@jlipps @sebv The taking of ganders, please if you will.
=> Made adb present check part of instantiation

lib/helpers.js, lib/logcat.js, lib/tools/adb-commands.js, lib/utils.js, package.json, test/functional/logcat-e2e-specs.js, test/helpers.js, test/unit/adb-commands-specs.js, test/unit/android-manifest-specs.js, test/unit/apk-signing-specs.js, test/unit/apk-utils-specs.js, test/unit/logcat-specs.js
- Logcat with es6+ and teen_process.
- Added android-22 and android-mnc
- @jlipps @sebv please review
=> Porting logcat to es6+ also adding functional and unit tests for it

.npmignore
How many of these are actually present?
=> Adding npmignore with not including build

lib/tools/adb-commands.js, test/functional/adb-commands-e2e-specs.js, test/unit/adb-commands-specs.js
=> Fixing defect with port forwarding

.gitignore, .npmignore
=> Adding coverage-e2e to gitingnore and npmignore

lib/helpers.js, lib/tools/android-manifest.js, package.json, test/functional/adb-commands-e2e-specs.js
In some environments there is no `unzip`. Try `gunzip` as well!
=> Check for unzip program

lib/helpers.js
There was another instance of unzip that would fail on some systems. :(. Fix it.
=> Fix the other instance of unzip

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
return null for appPackage and appActivity
@imurchie
=> getFocusedPackageAndActivity fix

lib/tools/adb-commands.js, lib/tools/apk-signing.js, lib/tools/system-calls.js, test/functional/adb-commands-e2e-specs.js, test/unit/adb-commands-specs.js
Part of `appium-android-driver` getSession fix.
@imurchie
=> implemented getPlatformVersion

README.md, lib/tools/apk-utils.js, test/functional/apk-utils-e2e-specs.js, test/unit/apk-utils-specs.js
please review @moizjv @imurchie
=> add startUri method so people can navigate directly into a deep view

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
This will be used to set the value immediately on an element, without Ui Automator.
=> Add method to send text to the device

lib/tools/adb-commands.js, lib/tools/system-calls.js
Especially where we are logging, then logging the same thing again, etc. etc. _ad nauseum_.
=> Clean up logging a bit

index.js, lib/adb.js, lib/tools/system-calls.js
not the 'ANDROID_ADB_SERVER_PORT' env var
=> only pay attention to the 'adbPort' opt

lib/tools/adb-commands.js
Also, once we have it, why not keep track of it?
=> Log getting api level

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Fixes https://github.com/appium/appium/issues/6366
=> Make sure we can get the activity

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Creating a new pull request to see if that helps get the CI build rolling.
=> Fix for multiple wait activities on Android (https://github.com/appium/appium-adb/issues/138)

README.md
We aren't working off 2.0 branch anymore.
=> Update badges on readme

lib/helpers.js, lib/tools/adb-commands.js
Fixes https://github.com/appium/appium/issues/3158.
Complements https://github.com/appium/appium-android-driver/pull/169.
=> Add screen orientation detection

lib/tools/system-calls.js
Fixes https://github.com/appium/appium/issues/6773
=> Fix call to errorAndThrow

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Switch parameter order as per https://github.com/appium/appium-adb/pull/173#issuecomment-251312979
=> Shift parameters for install

lib/tools/adb-commands.js
Fixes https://github.com/appium/appium/issues/6978
=> Trim the string, not the promise

lib/tools/adb-commands.js, test/functional/adb-commands-e2e-specs.js, test/unit/adb-commands-specs.js
=> Added utility method to remove forwarded port

lib/tools/adb-commands.js, test/functional/adb-commands-e2e-specs.js, test/unit/adb-commands-specs.js
Req Ticket: #https://github.com/appium/appium/issues/3210
cc: @jlipps, @imurchie
=> added utility methods for fetching model, manufacturer and screen size 

lib/tools/system-calls.js
The comments use the word "stupid" will not make many people feel very well.
It seems that there is something wrong with the adb
=> Modify the comments desctiption of system-calls.js

lib/helpers.js, lib/tools/system-calls.js
=> Use avdmanager for Android SDK 25+

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
There method will be then useful together with https://github.com/appium/io.appium.settings/pull/7
=> Add helper methods for getting packages info

lib/tools/adb-commands.js, lib/tools/system-calls.js, test/unit/syscalls-specs.js
Fixes https://github.com/appium/appium/issues/6894
=> Try to restart adbd as root on reboot failure

lib/tools/adb-commands.js, lib/tools/adb-emu-commands.js, test/unit/adb-commands-specs.js
Please do not merge this PR before https://github.com/appium/io.appium.settings/pull/7 is merged and published
=> Update network switch procedure and separate simulator calls from real device calls

lib/tools/android-manifest.js
Please see https://github.com/appium/appium/issues/8221 for detail.
=> Fix the wrong APK path reference ( #8221)

lib/tools/system-calls.js
Fixes https://github.com/appium/appium/issues/8234
=> Log error from unroot but continue

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
I had to create fork from scratch to assign my email with commit.
=> Fix behavor with spaces

.travis.yml, test/functional/adb-commands-e2e-specs.js, test/functional/apk-utils-e2e-specs.js, test/functional/logcat-e2e-specs.js, test/functional/setup.js, test/functional/syscalls-e2e-specs.js
Run functional tests in Travis.
=> Update travis config to run e2e tests

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
I ran across an error locally. The current implementation will crash the server full stop.run
=> Handle telnet connection error

.travis.yml, lib/tools/apk-utils.js, lib/tools/system-calls.js, package.json, test/functional/setup.js, test/functional/syscalls-e2e-specs.js
The reboot test is flakey. Extend travis timeout, and allows configuration of reboot retries.
=> 	Make reboot test have long timeout

lib/tools/adb-commands.js
Addresses https://github.com/appium/appium/issues/8461
=> Split long permission granting queries into chunks to avoid adb failures

lib/tools/system-calls.js, test/unit/syscalls-specs.js
Both are being used as _ad hoc_ commands elsewhere, so should be part of the API.
=> Add killServer and fileSize methods

lib/tools/apk-utils.js
If the activity is already a fully-qualified name, do not append package names.
See https://github.com/appium/appium/issues/8868
=> Do not append package name if fully-qualified activity given

lib/tools/apk-utils.js
it is necessasry to add await symbol, cause it is asynchronous
=> add await to  getPackageInfo method

lib/tools/adb-emu-commands.js, test/unit/adb-emu-commands-specs.js
Add a method to change the emulator network speed emulation.
=> Add netspeed method for emulators

gulpfile.js, lib/adb.js, lib/helpers.js, lib/logcat.js, lib/tools/adb-commands.js, package.json, test/functional/adb-commands-e2e-specs.js, test/unit/adb-emu-commands-specs.js, test/unit/helper-specs.js
=> Update eslint and deps

lib/tools/adb-commands.js, lib/tools/adb-emu-commands.js, lib/tools/android-manifest.js, lib/tools/apk-utils.js
This should be done anyway at some point of time. I will add docstring to other methods in some other PR when I have time.
=> Add documentation to adb methods

lib/tools/adb-commands.js, lib/tools/adb-emu-commands.js, lib/tools/android-manifest.js, lib/tools/apk-signing.js, lib/tools/apk-utils.js, lib/tools/system-calls.js
Used these tutorials:
https://stackoverflow.com/questions/28763257/jsdoc-return-object-structure
http://usejsdoc.org/tags-type.html
=> Improve existing docstrings and add missing ones.

lib/tools/apk-utils.js
Addresses https://github.com/appium/appium/issues/9196
=> Check if the package is installed before to uninstall it

lib/tools/apk-utils.js
This should finally fix https://github.com/appium/appium/issues/9196
=> Add missing await

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
Replaces https://github.com/appium/appium-adb/pull/257
=> Force process killing if the initial kill command fails

test/unit/helper-specs.js, test/unit/logcat-specs.js, test/unit/syscalls-specs.js
Skip some tests addressed in https://github.com/appium/appium-adb/pull/271#issuecomment-346260317
They fail on the current master branch. So, I'll skip once and try to fix them after https://github.com/appium/appium-adb/pull/271
=> skip failed tests on Travis

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
This PR is to fix an issue related to adb pm dump command parsing. You can find more details about the issue https://github.com/appium/appium/issues/10018#issuecomment-3588045460.
I also added some tests as well to cover both cases. Please let me know if it is not needed.
=> fixes regex to parse pkg permissions

lib/helpers.js, lib/tools/system-calls.js
Simplify the code and make search operation to perform faster. Also, fixed  a bug in the folders sorting algorithm.
=> Refactor binary path location detection

lib/tools/android-manifest.js
Addresses https://github.com/appium/appium/issues/10120#issuecomment-364227397
=> Fix getting path to apkanalyzer

lib/tools/adb-commands.js, test/functional/adb-commands-e2e-specs.js
This is the part of https://github.com/appium/appium/issues/4446 implementation
=> Add bugreport feature

lib/helpers.js, test/unit/helper-specs.js
The previous algorithm was not very precise and it required a source update each time there is new Android SDK
=> Improve the algorithm for finding the recent installed platform version

lib/helpers.js, lib/tools/android-manifest.js, test/functional/helpers-specs-e2e-specs.js
This should help to get rid of some custom jar dependencies and improve/optimize manifest helpers in general
=> Improve manifest operations

lib/tools/apk-utils.js, test/functional/adb-commands-e2e-specs.js, test/unit/apk-utils-specs.js
The current algorithm only uses the stuff provided by `aapt` without custom jars. Also now it properly handles plural forms.
=> Improve strings extraction algorithm

lib/logcat.js, lib/tools/adb-commands.js
The idea is to add then a special method into android driver, which would broadcast adb logs via websocket in "realtime"
=> Add a possibility to emit adb log output events

test/unit/adb-commands-specs.js, test/unit/adb-emu-commands-specs.js, test/unit/android-manifest-specs.js, test/unit/apk-signing-specs.js, test/unit/apk-utils-specs.js, test/unit/helper-specs.js, test/unit/logcat-specs.js, test/unit/syscalls-specs.js
=> De-clutter unit tests

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Addresses https://github.com/appium/appium/issues/4489
=> Use mCurrentFocus along with mFocusedApp to detect the focused activity

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
It looks like the dumpsys response might be a bit more complicated than I thought.
=> Tune mCurrentFocus parsing regexp

lib/helpers.js
Part of https://github.com/appium/appium/issues/10685
=> Fix buffer usage

lib/tools/system-calls.js
Addresses https://github.com/appium/appium/issues/10725
=> Fix the error message if the command is of type string

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
Addresses the case described in https://github.com/appium/appium/issues/10859
=> Improve the upgrade condition

lib/helpers.js, lib/tools/system-calls.js, test/functional/syscalls-e2e-specs.js
Related to https://github.com/appium/appium-android-driver/pull/386
=> Add a method for custom certificate installation

lib/tools/system-calls.js
Addresses 
https://github.com/appium/appium/issues/11116
=> Update the regexp for size parsing

lib/tools/system-calls.js
https://unix.stackexchange.com/questions/206909/and-s-in-permission-strings
=> Fix the list of acceptable chars in permissions string

lib/tools/system-calls.js
Thanks to @pr4bh4sh for assistance with testing
=> Fix and improve MITM certificate installation algorithm

lib/tools/system-calls.js
See https://github.com/appium/appium/issues/10964#issuecomment-410871599
=> Do not throw an exception if emulator process dies asynchronously

lib/tools/adb-commands.js
The PR is based on https://github.com/appium/io.appium.settings/pull/16
=> Add a possibility to retrieve geo location

lib/tools/adb-commands.js
The PR depends on https://github.com/appium/io.appium.settings/pull/18
=> Add a helper for performing editor actions

lib/tools/system-calls.js
Tune some findings from https://github.com/appium/appium/issues/10964
=> Update MITM certificate installation

lib/tools/apks-utils.js, package.json
This should resolve race condition issues while extracting apks in parallel testing sessions
=> Synchronize apks caching

lib/tools/adb-commands.js
=> Refactor isSoftKeyboardPresent call

lib/tools/adb-commands.js, lib/tools/system-calls.js, test/unit/adb-commands-specs.js, test/unit/apk-utils-specs.js
I observe a need to in such shortcut for commands that can only be executed under root privileges.
=> Add an option to shell command for running as root

lib/tools/apk-signing.js, test/unit/apk-signing-specs.js
Hopefully addresses https://github.com/appium/appium/issues/11704
=> Workaround NodeJS bug while executing scripts on Windows

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
This refactoring will help to resolve some discrepancies in UIA2 driver and improves the code quality of appium-adb module
=> Move application install state detector into a separate method

lib/tools/apk-utils.js
Fixed the issue where newer version state was returned while version numbers where the same.
=> Tune versions comparison

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
Fully addresses https://github.com/appium/appium-adb/issues/395 this time
=> Update ps output parsing logic

lib/tools/apk-utils.js, lib/tools/apks-utils.js, lib/tools/system-calls.js, test/functional/adb-commands-e2e-specs.js, test/unit/apk-utils-specs.js
alternative of https://github.com/appium/appium-adb/pull/410
what about this?
=> add timeoutCapName to show what cap is required by the timeout

lib/adb.js, lib/tools/adb-commands.js, lib/tools/adb-emu-commands.js, lib/tools/android-manifest.js, lib/tools/apk-signing.js, lib/tools/apk-utils.js, lib/tools/apks-utils.js, lib/tools/system-calls.js, test/.eslintrc
Very simple change, which cleans up the stack traces and makes them more useable.
=> Make sure all functions have names

lib/tools/adb-commands.js
https://github.com/appium/appium/issues/12311
https://developer.android.com/preview/non-sdk-q
=> add hidden_api_policy for Q

test/functional/apk-utils-e2e-specs.js
https://travis-ci.org/appium/appium-adb/jobs/508475670
=> Retry the flaky test

lib/tools/apk-signing.js
Related to https://github.com/appium/appium/issues/12355
=> Throw proper exception if the application is not writeable for zipalign

lib/tools/adb-commands.js
This should resolve issues like https://github.com/appium/java-client/issues/850
=> Relax process lookup logic

lib/tools/system-calls.js
Resolves https://discuss.appium.io/t/android-emulator-is-being-started-again/25681
=> Make emulator name comparison case insensitive

lib/tools/system-calls.js
Addresses additional comments to https://github.com/appium/appium-adb/pull/442
=> Remove the unnecessary logs

.travis.yml, ci-jobs/ci.yml, ci-jobs/mocha-config.json, ci-jobs/nightly.yml, ci-jobs/pr-validation.yml, ci-jobs/templates/android-e2e-template.yml, lib/tools/apk-utils.js, package.json, test/functional/setup.js
Update Travis config. Also move Azure build to use multiple reporters, and remove "build" stage in tests, since building happens in all the other stages.
=> Fix Travis build

.travis.yml, lib/adb.js, lib/helpers.js, lib/tools/system-calls.js, test/functional/helpers-specs-e2e-specs.js, test/unit/android-manifest-specs.js
Addresses https://github.com/appium/appium/issues/12735
=> Use ANDROID_SDK_ROOT along with ANDROID_HOME

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
As same as https://github.com/appium/WebDriverAgent/pull/184
(Will wait for 1.14.0 release)
=> add getting current timezone

ci-jobs/nightly.yml, test/unit/adb-commands-specs.js, test/unit/logcat-specs.js
Fix unit tests to adapt to new Sinon syntax
=> Fix outdated unit tests

lib/tools/adb-commands.js
https://github.com/appium/appium/issues/12867
=> Add handling of altitude property to setGeoLocation

lib/tools/apk-utils.js
https://github.com/appium/appium/issues/13663
=> fix: consider waitDuration value if it is greater or equal to zero

lib/tools/adb-commands.js
Based on https://github.com/appium/io.appium.settings/commit/d78af799b49dc02574dfabf98984fb1abb64e2bd
=> feat: Retrieve Android notifications

lib/tools/android-manifest.js
=> refactor: Prefer ApkReader to get the target SDK version

lib/helpers.js, lib/tools/adb-commands.js, test/unit/helper-specs.js
Based on https://github.com/appium/io.appium.settings/pull/55
=> feat: Add a helper method to retrieve SMS list

lib/tools/settings-client-commands.js, package.json
https://github.com/appium/appium/issues/13154
=> feat: Allow to type Unicode characters

lib/tools/apk-utils.js
https://github.com/appium/appium/issues/13970
=> fix: Apply the fallback procedure if application caching fails

lib/tools/adb-commands.js, test/unit/adb-commands-specs.js
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=8104&view=logs&j=25e09710-041d-5e84-9b7c-7583b448ad52&t=12c02101-029e-5dde-340b-a9ad73ea9568&l=1109
=> chore: Avoid throwing exceptions if the given process to kill does not exist

lib/helpers.js, test/unit/helper-specs.js
https://github.com/appium/appium/issues/14076
=> support give permission to car

lib/tools/apk-utils.js
This PR will fix below issue.
https://github.com/appium/appium/issues/14180
=> feat: Add an option to control intent wait for a started URI

ci-jobs/scripts/start-emulator.sh, test/functional/adb-commands-e2e-specs.js
Addresses https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=9690&view=logs&j=ea3a8326-8ae1-5392-57d8-7054c454cdab&t=453d04a0-cd6a-564e-7067-3aada09486e9
=> fix: Update emulator startup logic

test/functional/adb-commands-e2e-specs.js
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=9800&view=logs&j=66f1e43a-163e-5d1c-9c47-72628325f4ea&t=60447e9b-2dbf-521f-937b-5146b289cd42
=> chore: make tests more stable

lib/adb.js, lib/tools/adb-commands.js
https://github.com/appium/appium/issues/14373
=> chore: Make sure the server is running upon init

index.js, lib/adb.js
Want to use `getSdkRootFromEnv` in appium-doctor :)
=> feat: expose getSdkRootFromEnv

lib/tools/system-calls.js
https://github.com/appium/appium/issues/14453
=> fix: Set device id and port on emulator startup

lib/adb.js, lib/tools/system-calls.js
https://github.com/appium/appium/issues/14773
=> feat: Make the usage of -delay-adb configurable on emulator startup

lib/tools/adb-commands.js, test/functional/adb-commands-e2e-specs.js
https://github.com/appium/appium/issues/14841#issuecomment-716107369
=> feat: Add helpers to deal with deviceidle whitelist

lib/tools/apk-signing.js
fixes https://github.com/appium/appium/issues/14724
=> fix: set CWD explicity when executing java -jar apksigner.jar

lib/helpers.js, lib/tools/apk-utils.js, lib/tools/settings-client-commands.js
https://discuss.appium.io/t/how-to-modify-wd-proxy-and-uiautomator2-source-code-to-support-unicode/33466/3
=> fix: Escape ampersand in command line arguments

lib/tools/apks-utils.js
https://github.com/appium/appium/issues/15887
=> refactor: Use bundletool to install .apks packages

lib/tools/index.js, lib/tools/lockmgmt.js, test/functional/lock-mgmt-e2e-specs.js
We could potentially speed up device unlocking on newer platforms with these helpers. Check https://newbedev.com/using-adb-to-change-the-screen-lock for more details.
=> feat: Add lock management utilities

lib/tools/adb-commands.js, lib/tools/settings-client-commands.js, test/unit/adb-commands-specs.js
https://github.com/appium/appium/issues/15943
=> chore: Add a pause to runInImeContext helper

lib/tools/adb-emu-commands.js, test/unit/adb-emu-commands-specs.js
Related to https://discuss.appium.io/t/android-emulator-device-pose-rotate/35073
=> chore: Update the list of available sensor values

lib/tools/settings-client-commands.js
Based on https://github.com/appium/io.appium.settings/pull/75
=> feat: Add a helper to run media scan

lib/tools/settings-client-commands.js
Based on https://github.com/appium/io.appium.settings
=> feat: Add a method for GPS cache refresh

.eslintrc, gulpfile.js, lib/helpers.js, lib/logcat.js, lib/logger.js, lib/tools/adb-commands.js, lib/tools/adb-emu-commands.js, lib/tools/android-manifest.js, lib/tools/apk-signing.js, lib/tools/apk-utils.js, lib/tools/apks-utils.js, lib/tools/lockmgmt.js, lib/tools/settings-client-commands.js, lib/tools/system-calls.js, package.json, test/functional/adb-commands-e2e-specs.js, test/functional/adb-e2e-specs.js, test/functional/android-manifest-e2e-specs.js, test/functional/syscalls-e2e-specs.js, test/unit/adb-commands-specs.js, test/unit/adb-emu-commands-specs.js, test/unit/apk-signing-specs.js, test/unit/apk-utils-specs.js, test/unit/helper-specs.js, test/unit/logcat-specs.js, test/unit/syscalls-specs.js
This is not really a breaking change (yet), but we anyway would like to do this in order to start bumping Android drivers.
=> refactor!: Switch the package to Appium2 modules

lib/tools/adb-commands.js, test/functional/adb-commands-e2e-specs.js
Based on https://stackoverflow.com/questions/12698814/get-launchable-activity-name-of-package-from-adb
=> feat: Add a helper to resolve launchable activity name

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
https://github.com/appium/appium/issues/17106
=> feat: Tune active activity/package names parsing for multi-screen systems

lib/tools/system-calls.js
Related to https://github.com/appium/appium/issues/17200
=> refactor: Detect if emulator is running by checking its services

lib/tools/system-calls.js
Related to https://github.com/appium/appium/issues/17279
=> chore: Add 'mount' to the list of required emulator services

lib/tools/adb-commands.js
Addresses https://github.com/appium/appium/issues/17422
=> fix: Try to broadcast airplane mode with root privileges on emulators

lib/tools/settings-client-commands.js
https://github.com/appium/appium/issues/17641
=> fix: defaultArgs and path call in refreshGeoLocationCache

lib/tools/apk-utils.js, lib/tools/settings-client-commands.js, lib/tools/system-calls.js, test/functional/apk-utils-e2e-specs.js, test/unit/adb-commands-specs.js
Related to https://github.com/appium/appium-uiautomator2-driver/pull/556/files#r1002775545
=> chore: Make sure settings app is running before broadcasting to it

lib/helpers.js, lib/tools/apk-signing.js, test/functional/syscalls-e2e-specs.js
Related to https://github.com/appium/appium/issues/18057
=> chore: Only fetch resource paths when they are requested

lib/tools/apk-utils.js, test/unit/apk-utils-specs.js
dumpsys also requests a bunch of extra info, which we don't need while detecting the fact of a successful app install
=> chore: Speed up app installation detection

.github/workflows/unit-test.yml, lib/helpers.js, test/unit/helper-specs.js
Fixes https://github.com/appium/appium/issues/19141
=> fix: JSON data parsing with extras

lib/tools/system-calls.js
Addresses https://github.com/appium/appium/issues/19266
=> fix: Fallback the boot detection if the device does not have reboot_readiness service

lib/adb.ts, lib/helpers.js, lib/logcat.js, lib/mixins.ts, lib/options.ts, lib/stubs.ts, lib/tools/aab-utils.js, lib/tools/adb-commands.js, lib/tools/adb-emu-commands.js, lib/tools/android-manifest.js, lib/tools/apk-signing.js, lib/tools/apk-utils.js, lib/tools/apks-utils.js, lib/tools/keyboard-commands.js, lib/tools/lockmgmt.js, lib/tools/settings-client-commands.js, lib/tools/system-calls.js, lib/tools/utf7.js, test/unit/adb-commands-specs.js, test/unit/adb-emu-commands-specs.js, tsconfig.json
BREAKING CHANGE: Some type declarations have been changed in order to make the compiler happy
=> feat!: Improve type declarations

lib/helpers.js, lib/stubs.ts, lib/tools/android-manifest.js, lib/tools/apk-utils.js, package.json
https://github.com/appium/appium/issues/19396#issuecomment-1805102161
The version bumped the debug package. The diff looks like has no code changes, so the usage should be the same
=> chore: change the reference of adbkit-apkreader

lib/tools/adb-commands.js
https://github.com/appium/appium/issues/19432
=> chore: Update the link in the troubleshooting error message

lib/adb.ts, lib/options.ts
https://appium.slack.com/archives/C02956V3H/p1712473953915389?thread_ts=1712413496.800729&cid=C02956V3H
=> fix: Respect the `udid` option

lib/logcat.js, lib/tools/adb-commands.js, package.json
These changes allow reducing of CPU usage. Also, the flow itself has been simplified and typed better
=> chore: Optimize logcat callbacks handling

lib/helpers.js, lib/stubs.ts, lib/tools/android-manifest.js, lib/tools/apk-utils.js, package.json, test/functional/helpers-specs-e2e-specs.js, test/unit/helper-specs.js
This reduces the amount of dependencies and also simplifies the code.
=> feat: Use aapt2 instead of ApkReader

lib/tools/apk-utils.js
Added better logging and refactored some methods to improve the validation process
=> chore: Streamline locale validation

lib/helpers.js, test/unit/helper-specs.js
To support https://github.com/appium/appium-adb/pull/772
=> feat: add support for activities with unicode chars

lib/helpers.js, test/unit/helper-specs.js
Addresses https://github.com/appium/appium-uiautomator2-driver/issues/856
=> fix: Do not prefix activity with package name if it already exists

lib/tools/app-commands.js, test/unit/adb-commands-specs.js
https://github.com/appium/appium-uiautomator2-driver/issues/925
=> fix: Update the logic for listing process ids belonging to an app
